using System;
using Microsoft.EntityFrameworkCore.Migrations;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace CarGame.Api.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:postgis", ",,");

            migrationBuilder.CreateTable(
                name: "Plates",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    country = table.Column<string>(type: "text", nullable: true),
                    abbreviation = table.Column<string>(type: "text", nullable: true),
                    code = table.Column<string>(type: "character varying(2)", maxLength: 2, nullable: true),
                    is_diplomat = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_plates", x => x.id);
                    table.CheckConstraint("CK_Plate_IsDiplomat_Code_Abbreviation", "((\"is_diplomat\" = TRUE AND \"code\" IS NOT NULL AND \"abbreviation\" IS NULL) OR (\"is_diplomat\" = FALSE AND \"abbreviation\" IS NOT NULL AND \"code\" IS NULL))");
                });

            migrationBuilder.CreateTable(
                name: "sightings",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    plate_id = table.Column<int>(type: "integer", nullable: false),
                    date = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "CURRENT_TIMESTAMP"),
                    description = table.Column<string>(type: "text", nullable: true),
                    is_diplomat = table.Column<bool>(type: "boolean", nullable: false),
                    diplomat_number = table.Column<int>(type: "integer", precision: 2, nullable: false),
                    location = table.Column<Point>(type: "geometry (point, 3067)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_sightings", x => x.id);
                    table.CheckConstraint("CK_plate_id_diplomat_number", "is_diplomat = false OR (diplomat_number IS NOT NULL AND diplomat_number >= 1 AND diplomat_number <= 99)");
                    table.ForeignKey(
                        name: "fk_sightings_plates_plate_id",
                        column: x => x.plate_id,
                        principalTable: "Plates",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Plates",
                columns: new[] { "id", "abbreviation", "code", "country", "is_diplomat" },
                values: new object[,]
                {
                    { 1, "AFG", null, "Afganistan", false },
                    { 2, "NL", null, "Alankomaat", false },
                    { 3, "NA", null, "Alankomaiden Antillit", false },
                    { 4, "AL", null, "Albania", false },
                    { 5, "GBA", null, "Alderney", false },
                    { 6, "DZ", null, "Algeria", false },
                    { 7, "AND", null, "Andorra", false },
                    { 8, "ANG", null, "Angola", false },
                    { 9, "AG", null, "Antigua ja Barbuda", false },
                    { 10, "RA", null, "Argentiina", false },
                    { 11, "AM", null, "Armenia", false },
                    { 12, "AUS", null, "Australia", false },
                    { 13, "AZ", null, "Azerbaidzhan", false },
                    { 14, "BS", null, "Bahamasaaret", false },
                    { 15, "BRN", null, "Bahrain", false },
                    { 16, "BD", null, "Bangladesh", false },
                    { 17, "BDS", null, "Barbados", false },
                    { 18, "B", null, "Belgia", false },
                    { 19, "BH", null, "Belize", false },
                    { 20, "DY", null, "Benin", false },
                    { 21, "BHT", null, "Bhutan", false },
                    { 22, "BOL", null, "Bolivia", false },
                    { 23, "BIH", null, "Bosnia-Hertsegovina", false },
                    { 24, "BW", null, "Botswana", false },
                    { 25, "BR", null, "Brasilia", false },
                    { 26, "BVI", null, "Brittiläiset Neitsytsaaret", false },
                    { 27, "BRU", null, "Brunei", false },
                    { 28, "BG", null, "Bulgaria", false },
                    { 29, "BF", null, "Burkina Faso", false },
                    { 30, "RU", null, "Burundi", false },
                    { 31, "RCH", null, "Chile", false },
                    { 32, "CR", null, "Costa Rica", false },
                    { 33, "DJI", null, "Dijibouti", false },
                    { 34, "WD", null, "Dominica", false },
                    { 35, "DOM", null, "Dominikaaninen tasavalta", false },
                    { 36, "EC", null, "Ecuador", false },
                    { 37, "ET", null, "Egypti", false },
                    { 38, "SV", null, "El Salvador", false },
                    { 39, "ER", null, "Eritrea", false },
                    { 40, "E", null, "Espanja", false },
                    { 41, "ZA", null, "Etelä-Afrikka", false },
                    { 42, "ETH", null, "Etiopia", false },
                    { 43, "FJI", null, "Fidzi", false },
                    { 44, "RP", null, "Filippiinit", false },
                    { 45, "FR", null, "Färsaaret", false },
                    { 46, "G", null, "Gabon", false },
                    { 47, "WAG", null, "Gambia", false },
                    { 48, "GE", null, "Georgia", false },
                    { 49, "GH", null, "Ghana", false },
                    { 50, "GBZ", null, "Gibraltar", false },
                    { 51, "WG", null, "Grenada", false },
                    { 52, "KN", null, "Grönlanti", false },
                    { 53, "GCA", null, "Guatemala", false },
                    { 54, "GBG", null, "Guernsey", false },
                    { 55, "RG", null, "Guinea", false },
                    { 56, "GNB", null, "Guinea-Bissau", false },
                    { 57, "GUY", null, "Guyana", false },
                    { 58, "RH", null, "Haiti", false },
                    { 59, "HN", null, "Honduras", false },
                    { 60, "HK", null, "Hong Kong", false },
                    { 61, "RI", null, "Indonesia", false },
                    { 62, "IND", null, "Intia", false },
                    { 63, "IRQ", null, "Irak", false },
                    { 64, "IR", null, "Iran", false },
                    { 65, "IRL", null, "Irlanti", false },
                    { 66, "IS", null, "Islanti", false },
                    { 67, "IL", null, "Israel", false },
                    { 68, "I", null, "Italia", false },
                    { 69, "TL", null, "Itä-Timor", false },
                    { 70, "A", null, "Itävalta", false },
                    { 71, "JA", null, "Jamaika", false },
                    { 72, "J", null, "Japani", false },
                    { 73, "YAR", null, "Jemen", false },
                    { 74, "GBJ", null, "Jersey", false },
                    { 75, "HKJ", null, "Jordania", false },
                    { 76, "K", null, "Kambodzha", false },
                    { 77, "CAM", null, "Kamerun", false },
                    { 78, "CDN", null, "Kanada", false },
                    { 79, "CV", null, "Kap Verde", false },
                    { 80, "KZ", null, "Kazakstan", false },
                    { 81, "EAK", null, "Kenia", false },
                    { 82, "RCA", null, "Keski-Afrikan tasavalta", false },
                    { 83, "PRC", null, "Kiinan kansantasavalta", false },
                    { 84, "KS", null, "Kirgisia", false },
                    { 85, "KIR", null, "Kiribati", false },
                    { 86, "CO", null, "Kolumbia", false },
                    { 87, "COM", null, "Komorit", false },
                    { 88, "ZRE", null, "Kongon demokraattinen tasavalta", false },
                    { 89, "RCB", null, "Kongon tasavalta", false },
                    { 90, "DVRK", null, "Korean demokraattinen kansantasavalta", false },
                    { 91, "ROK", null, "Korean tasavalta", false },
                    { 92, "RKS", null, "Kosovo", false },
                    { 93, "GR", null, "Kreikka", false },
                    { 94, "HR", null, "Kroatia", false },
                    { 95, "CU", null, "Kuuba", false },
                    { 96, "KWT", null, "Kuwait", false },
                    { 97, "CY", null, "Kypros", false },
                    { 98, "LAO", null, "Laos", false },
                    { 99, "LV", null, "Latvia", false },
                    { 100, "LS", null, "Lesotho", false },
                    { 101, "RL", null, "Libanon", false },
                    { 102, "LB", null, "Liberia", false },
                    { 103, "LAR", null, "Libya", false },
                    { 104, "FL", null, "Liechtenstein", false },
                    { 105, "LT", null, "Liettua", false },
                    { 106, "L", null, "Luxemburg", false },
                    { 107, "DARS", null, "Länsi-Sahara", false },
                    { 108, "RM", null, "Madagaskar", false },
                    { 109, "NMK", null, "Pohjois-Makedonia", false },
                    { 110, "MW", null, "Malawi", false },
                    { 111, "MV", null, "Malediivit", false },
                    { 112, "MAL", null, "Malesia", false },
                    { 113, "RMM", null, "Mali", false },
                    { 114, "M", null, "Malta", false },
                    { 115, "GBM", null, "Man-saari", false },
                    { 116, "MA", null, "Marokko", false },
                    { 117, "MH", null, "Marshallinsaaret", false },
                    { 118, "RIM", null, "Mauritania", false },
                    { 119, "MS", null, "Mauritius", false },
                    { 120, "MEX", null, "Meksiko", false },
                    { 121, "FSM", null, "Mikronesia", false },
                    { 122, "MD", null, "Moldova", false },
                    { 123, "MC", null, "Monaco", false },
                    { 124, "MGL", null, "Mongolia", false },
                    { 125, "MNE", null, "Montenegro", false },
                    { 126, "MOC", null, "Mosambik", false },
                    { 127, "BUR", null, "Myanmar", false },
                    { 128, "NAM", null, "Namibia", false },
                    { 129, "NAU", null, "Nauru", false },
                    { 130, "NEP", null, "Nepal", false },
                    { 131, "NIC", null, "Nicaragua", false },
                    { 132, "RN", null, "Niger", false },
                    { 133, "WAN", null, "Nigeria", false },
                    { 134, "N", null, "Norja", false },
                    { 135, "CI", null, "Norsunluurannikko", false },
                    { 136, "OM", null, "Oman", false },
                    { 137, "PK", null, "Pakistan", false },
                    { 138, "PAL", null, "Palau", false },
                    { 139, "PS", null, "Palestiina", false },
                    { 140, "PA", null, "Panama", false },
                    { 141, "PNG", null, "Papua-Uusi Guinea", false },
                    { 142, "PY", null, "Paraguay", false },
                    { 143, "PE", null, "Peru", false },
                    { 144, "P", null, "Portugali", false },
                    { 145, "PL", null, "Puola", false },
                    { 146, "GQ", null, "Päiväntasaajan Guinea", false },
                    { 147, "Q", null, "Qatar", false },
                    { 148, "F", null, "Ranska", false },
                    { 149, "RO", null, "Romania", false },
                    { 150, "RWA", null, "Ruanda", false },
                    { 151, "S", null, "Ruotsi", false },
                    { 152, "SCN", null, "Saint Kitts ja Nevis", false },
                    { 153, "WL", null, "Saint Lucia", false },
                    { 154, "WV", null, "Saint Vincent ja Grenadiinit", false },
                    { 155, "D", null, "Saksa", false },
                    { 156, "SOL", null, "Salomonsaaret", false },
                    { 157, "Z", null, "Sambia", false },
                    { 158, "WS", null, "Samoa", false },
                    { 159, "RSM", null, "San Marino", false },
                    { 160, "STP", null, "São Tomé ja Príncipe", false },
                    { 161, "SA", null, "Saudi-Arabia", false },
                    { 162, "SN", null, "Senegal", false },
                    { 163, "SRB", null, "Serbia", false },
                    { 164, "SY", null, "Seychellit", false },
                    { 165, "WAL", null, "Sierra Leone", false },
                    { 166, "SGP", null, "Singapore", false },
                    { 167, "SK", null, "Slovakia", false },
                    { 168, "SLO", null, "Slovenia", false },
                    { 169, "SO", null, "Somalia", false },
                    { 170, "CL", null, "Sri Lanka", false },
                    { 171, "SUD", null, "Sudan", false },
                    { 172, "FIN", null, "Suomi", false },
                    { 173, "SME", null, "Surinam", false },
                    { 174, "SD", null, "Swazimaa", false },
                    { 175, "CH", null, "Sveitsi", false },
                    { 176, "SYR", null, "Syyria", false },
                    { 177, "TJ", null, "Tadzikistan", false },
                    { 178, "RC", null, "Taiwan", false },
                    { 179, "EAT", null, "Tansania", false },
                    { 180, "DK", null, "Tanska", false },
                    { 181, "T", null, "Thaimaa", false },
                    { 182, "TG", null, "Togo", false },
                    { 183, "TO", null, "Tonga", false },
                    { 184, "TT", null, "Trinidad ja Tobago", false },
                    { 185, "TD", null, "Tšad;TCH", false },
                    { 186, "CZ", null, "Tšekki", false },
                    { 187, "TN", null, "Tunisia", false },
                    { 188, "TR", null, "Turkki", false },
                    { 189, "TM", null, "Turkmenistan", false },
                    { 190, "TUV", null, "Tuvalu", false },
                    { 191, "EAU", null, "Uganda", false },
                    { 192, "UA", null, "Ukraina", false },
                    { 193, "H", null, "Unkari", false },
                    { 194, "ROU", null, "Uruguay", false },
                    { 195, "NZ", null, "Uusi-Seelanti", false },
                    { 196, "UZ", null, "Uzbekistan", false },
                    { 197, "BY", null, "Valko-Venäjä", false },
                    { 198, "VU", null, "Vanuatu", false },
                    { 199, "V", null, "Vatikaani", false },
                    { 200, "YV", null, "Venezuela", false },
                    { 201, "RUS", null, "Venäjä", false },
                    { 202, "VN", null, "Vietnam", false },
                    { 203, "EST", null, "Viro", false },
                    { 204, "UAE", null, "Yhdistyneet Arabiemiirikunnat", false },
                    { 205, "GB", null, "Yhdistynyt Kuningaskunta", false },
                    { 206, "USA", null, "Yhdysvallat", false },
                    { 207, "ZW", null, "Zimbabwe", false },
                    { 208, null, "10", "Saksa", true },
                    { 209, null, "12", "Yhdysvallat", true },
                    { 210, null, "14", "Argentiina", true },
                    { 211, null, "15", "Itävalta", true },
                    { 212, null, "16", "Belgia", true },
                    { 213, null, "17", "Brasilia", true },
                    { 214, null, "18", "Bulgaria", true },
                    { 215, null, "19", "Kanada", true },
                    { 216, null, "20", "Kiina", true },
                    { 217, null, "21", "Etelä-Korea", true },
                    { 218, null, "23", "Kuuba", true },
                    { 219, null, "24", "Tanska", true },
                    { 220, null, "25", "Egypti", true },
                    { 221, null, "26", "Espanja", true },
                    { 222, null, "27", "Ranska", true },
                    { 223, null, "28", "Iso-Britannia", true },
                    { 224, null, "29", "Unkari", true },
                    { 225, null, "30", "Intia", true },
                    { 226, null, "31", "Indonesia", true },
                    { 227, null, "32", "Irak", true },
                    { 228, null, "33", "Israel", true },
                    { 229, null, "34", "Italia", true },
                    { 230, null, "35", "Japani", true },
                    { 231, null, "36", "Meksiko", true },
                    { 232, null, "37", "Norja", true },
                    { 233, null, "38", "Hollanti", true },
                    { 234, null, "39", "Peru", true },
                    { 235, null, "40", "Puola", true },
                    { 236, null, "41", "Portugali", true },
                    { 237, null, "42", "Romania", true },
                    { 238, null, "43", "Ruotsi", true },
                    { 239, null, "44", "Sveitsi", true },
                    { 240, null, "46", "Turkki", true },
                    { 241, null, "47", "Venäjä", true },
                    { 242, null, "48", "Venezuela", true },
                    { 243, null, "49", "Serbia", true },
                    { 244, null, "50", "Etelä-Afrikka", true },
                    { 245, null, "51", "Kreikka", true },
                    { 246, null, "55", "Itämeren suojelukomissio", true },
                    { 247, null, "56", "Iran", true },
                    { 248, null, "57", "UNU-WIDER", true },
                    { 249, null, "58", "Chile", true },
                    { 250, null, "59", "Viro", true },
                    { 251, null, "60", "Latvia", true },
                    { 252, null, "61", "Irlanti", true },
                    { 253, null, "62", "Ukraina", true },
                    { 254, null, "63", "Slovakia", true },
                    { 255, null, "64", "Tšekki", true },
                    { 256, null, "65", "Liettua", true },
                    { 257, null, "66", "Kansainvälinen siirtolaisuusjärjestö", true },
                    { 258, null, "67", "Marokko", true },
                    { 259, null, "68", "Islanti", true },
                    { 260, null, "69", "Kroatia", true },
                    { 261, null, "71", "Kypros", true },
                    { 262, null, "74", "Tunisia", true },
                    { 263, null, "76", "Malesia", true },
                    { 264, null, "77", "Vietnam", true },
                    { 265, null, "78", "Thaimaa", true },
                    { 266, null, "79", "Euroopan kemikaalivirasto", true },
                    { 267, null, "80", "Saudi-Arabia", true },
                    { 268, null, "82", "Georgia", true },
                    { 269, null, "83", "Pohjoismaiden investointipankki", true },
                    { 270, null, "84", "Liberia", true },
                    { 271, null, "85", "Valko-Venäjä", true },
                    { 272, null, "86", "Kazakstan", true },
                    { 273, null, "87", "Kolumbia", true },
                    { 274, null, "88", "Uruguay", true },
                    { 275, null, "89", "Palestiina", true },
                    { 276, null, "90", "Namibia", true },
                    { 277, null, "91", "Algeria", true },
                    { 278, null, "92", "Yhdistyneet arabiemiirikunnat", true }
                });

            migrationBuilder.CreateIndex(
                name: "ix_sightings_plate_id",
                table: "sightings",
                column: "plate_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "sightings");

            migrationBuilder.DropTable(
                name: "Plates");
        }
    }
}
