// <auto-generated />
using System;
using CarGame.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarGame.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230910172146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarGame.Api.Entites.Plate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<bool>("IsDiplomat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_diplomat");

                    b.HasKey("Id")
                        .HasName("pk_plates");

                    b.ToTable("Plates", null, t =>
                        {
                            t.HasCheckConstraint("CK_Plate_IsDiplomat_Code_Abbreviation", "((\"is_diplomat\" = TRUE AND \"code\" IS NOT NULL AND \"abbreviation\" IS NULL) OR (\"is_diplomat\" = FALSE AND \"abbreviation\" IS NOT NULL AND \"code\" IS NULL))");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AFG",
                            Country = "Afganistan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NL",
                            Country = "Alankomaat",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NA",
                            Country = "Alankomaiden Antillit",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "AL",
                            Country = "Albania",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "GBA",
                            Country = "Alderney",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "DZ",
                            Country = "Algeria",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "AND",
                            Country = "Andorra",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "ANG",
                            Country = "Angola",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "AG",
                            Country = "Antigua ja Barbuda",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "RA",
                            Country = "Argentiina",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "AM",
                            Country = "Armenia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "AUS",
                            Country = "Australia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "AZ",
                            Country = "Azerbaidzhan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "BS",
                            Country = "Bahamasaaret",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "BRN",
                            Country = "Bahrain",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "BD",
                            Country = "Bangladesh",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "BDS",
                            Country = "Barbados",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "B",
                            Country = "Belgia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "BH",
                            Country = "Belize",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "DY",
                            Country = "Benin",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "BHT",
                            Country = "Bhutan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "BOL",
                            Country = "Bolivia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "BIH",
                            Country = "Bosnia-Hertsegovina",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "BW",
                            Country = "Botswana",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "BR",
                            Country = "Brasilia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "BVI",
                            Country = "Brittiläiset Neitsytsaaret",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "BRU",
                            Country = "Brunei",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "BG",
                            Country = "Bulgaria",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "BF",
                            Country = "Burkina Faso",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "RU",
                            Country = "Burundi",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "RCH",
                            Country = "Chile",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "CR",
                            Country = "Costa Rica",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 33,
                            Abbreviation = "DJI",
                            Country = "Dijibouti",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 34,
                            Abbreviation = "WD",
                            Country = "Dominica",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 35,
                            Abbreviation = "DOM",
                            Country = "Dominikaaninen tasavalta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 36,
                            Abbreviation = "EC",
                            Country = "Ecuador",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 37,
                            Abbreviation = "ET",
                            Country = "Egypti",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 38,
                            Abbreviation = "SV",
                            Country = "El Salvador",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 39,
                            Abbreviation = "ER",
                            Country = "Eritrea",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 40,
                            Abbreviation = "E",
                            Country = "Espanja",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 41,
                            Abbreviation = "ZA",
                            Country = "Etelä-Afrikka",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 42,
                            Abbreviation = "ETH",
                            Country = "Etiopia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 43,
                            Abbreviation = "FJI",
                            Country = "Fidzi",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 44,
                            Abbreviation = "RP",
                            Country = "Filippiinit",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 45,
                            Abbreviation = "FR",
                            Country = "Färsaaret",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 46,
                            Abbreviation = "G",
                            Country = "Gabon",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 47,
                            Abbreviation = "WAG",
                            Country = "Gambia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 48,
                            Abbreviation = "GE",
                            Country = "Georgia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 49,
                            Abbreviation = "GH",
                            Country = "Ghana",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 50,
                            Abbreviation = "GBZ",
                            Country = "Gibraltar",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 51,
                            Abbreviation = "WG",
                            Country = "Grenada",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 52,
                            Abbreviation = "KN",
                            Country = "Grönlanti",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 53,
                            Abbreviation = "GCA",
                            Country = "Guatemala",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 54,
                            Abbreviation = "GBG",
                            Country = "Guernsey",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 55,
                            Abbreviation = "RG",
                            Country = "Guinea",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 56,
                            Abbreviation = "GNB",
                            Country = "Guinea-Bissau",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 57,
                            Abbreviation = "GUY",
                            Country = "Guyana",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 58,
                            Abbreviation = "RH",
                            Country = "Haiti",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 59,
                            Abbreviation = "HN",
                            Country = "Honduras",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 60,
                            Abbreviation = "HK",
                            Country = "Hong Kong",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 61,
                            Abbreviation = "RI",
                            Country = "Indonesia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 62,
                            Abbreviation = "IND",
                            Country = "Intia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 63,
                            Abbreviation = "IRQ",
                            Country = "Irak",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 64,
                            Abbreviation = "IR",
                            Country = "Iran",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 65,
                            Abbreviation = "IRL",
                            Country = "Irlanti",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 66,
                            Abbreviation = "IS",
                            Country = "Islanti",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 67,
                            Abbreviation = "IL",
                            Country = "Israel",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 68,
                            Abbreviation = "I",
                            Country = "Italia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 69,
                            Abbreviation = "TL",
                            Country = "Itä-Timor",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 70,
                            Abbreviation = "A",
                            Country = "Itävalta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 71,
                            Abbreviation = "JA",
                            Country = "Jamaika",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 72,
                            Abbreviation = "J",
                            Country = "Japani",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 73,
                            Abbreviation = "YAR",
                            Country = "Jemen",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 74,
                            Abbreviation = "GBJ",
                            Country = "Jersey",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 75,
                            Abbreviation = "HKJ",
                            Country = "Jordania",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 76,
                            Abbreviation = "K",
                            Country = "Kambodzha",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 77,
                            Abbreviation = "CAM",
                            Country = "Kamerun",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 78,
                            Abbreviation = "CDN",
                            Country = "Kanada",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 79,
                            Abbreviation = "CV",
                            Country = "Kap Verde",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 80,
                            Abbreviation = "KZ",
                            Country = "Kazakstan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 81,
                            Abbreviation = "EAK",
                            Country = "Kenia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 82,
                            Abbreviation = "RCA",
                            Country = "Keski-Afrikan tasavalta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 83,
                            Abbreviation = "PRC",
                            Country = "Kiinan kansantasavalta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 84,
                            Abbreviation = "KS",
                            Country = "Kirgisia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 85,
                            Abbreviation = "KIR",
                            Country = "Kiribati",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 86,
                            Abbreviation = "CO",
                            Country = "Kolumbia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 87,
                            Abbreviation = "COM",
                            Country = "Komorit",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 88,
                            Abbreviation = "ZRE",
                            Country = "Kongon demokraattinen tasavalta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 89,
                            Abbreviation = "RCB",
                            Country = "Kongon tasavalta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 90,
                            Abbreviation = "DVRK",
                            Country = "Korean demokraattinen kansantasavalta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 91,
                            Abbreviation = "ROK",
                            Country = "Korean tasavalta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 92,
                            Abbreviation = "RKS",
                            Country = "Kosovo",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 93,
                            Abbreviation = "GR",
                            Country = "Kreikka",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 94,
                            Abbreviation = "HR",
                            Country = "Kroatia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 95,
                            Abbreviation = "CU",
                            Country = "Kuuba",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 96,
                            Abbreviation = "KWT",
                            Country = "Kuwait",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 97,
                            Abbreviation = "CY",
                            Country = "Kypros",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 98,
                            Abbreviation = "LAO",
                            Country = "Laos",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 99,
                            Abbreviation = "LV",
                            Country = "Latvia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 100,
                            Abbreviation = "LS",
                            Country = "Lesotho",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 101,
                            Abbreviation = "RL",
                            Country = "Libanon",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 102,
                            Abbreviation = "LB",
                            Country = "Liberia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 103,
                            Abbreviation = "LAR",
                            Country = "Libya",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 104,
                            Abbreviation = "FL",
                            Country = "Liechtenstein",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 105,
                            Abbreviation = "LT",
                            Country = "Liettua",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 106,
                            Abbreviation = "L",
                            Country = "Luxemburg",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 107,
                            Abbreviation = "DARS",
                            Country = "Länsi-Sahara",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 108,
                            Abbreviation = "RM",
                            Country = "Madagaskar",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 109,
                            Abbreviation = "NMK",
                            Country = "Pohjois-Makedonia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 110,
                            Abbreviation = "MW",
                            Country = "Malawi",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 111,
                            Abbreviation = "MV",
                            Country = "Malediivit",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 112,
                            Abbreviation = "MAL",
                            Country = "Malesia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 113,
                            Abbreviation = "RMM",
                            Country = "Mali",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 114,
                            Abbreviation = "M",
                            Country = "Malta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 115,
                            Abbreviation = "GBM",
                            Country = "Man-saari",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 116,
                            Abbreviation = "MA",
                            Country = "Marokko",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 117,
                            Abbreviation = "MH",
                            Country = "Marshallinsaaret",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 118,
                            Abbreviation = "RIM",
                            Country = "Mauritania",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 119,
                            Abbreviation = "MS",
                            Country = "Mauritius",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 120,
                            Abbreviation = "MEX",
                            Country = "Meksiko",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 121,
                            Abbreviation = "FSM",
                            Country = "Mikronesia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 122,
                            Abbreviation = "MD",
                            Country = "Moldova",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 123,
                            Abbreviation = "MC",
                            Country = "Monaco",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 124,
                            Abbreviation = "MGL",
                            Country = "Mongolia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 125,
                            Abbreviation = "MNE",
                            Country = "Montenegro",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 126,
                            Abbreviation = "MOC",
                            Country = "Mosambik",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 127,
                            Abbreviation = "BUR",
                            Country = "Myanmar",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 128,
                            Abbreviation = "NAM",
                            Country = "Namibia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 129,
                            Abbreviation = "NAU",
                            Country = "Nauru",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 130,
                            Abbreviation = "NEP",
                            Country = "Nepal",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 131,
                            Abbreviation = "NIC",
                            Country = "Nicaragua",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 132,
                            Abbreviation = "RN",
                            Country = "Niger",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 133,
                            Abbreviation = "WAN",
                            Country = "Nigeria",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 134,
                            Abbreviation = "N",
                            Country = "Norja",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 135,
                            Abbreviation = "CI",
                            Country = "Norsunluurannikko",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 136,
                            Abbreviation = "OM",
                            Country = "Oman",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 137,
                            Abbreviation = "PK",
                            Country = "Pakistan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 138,
                            Abbreviation = "PAL",
                            Country = "Palau",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 139,
                            Abbreviation = "PS",
                            Country = "Palestiina",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 140,
                            Abbreviation = "PA",
                            Country = "Panama",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 141,
                            Abbreviation = "PNG",
                            Country = "Papua-Uusi Guinea",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 142,
                            Abbreviation = "PY",
                            Country = "Paraguay",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 143,
                            Abbreviation = "PE",
                            Country = "Peru",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 144,
                            Abbreviation = "P",
                            Country = "Portugali",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 145,
                            Abbreviation = "PL",
                            Country = "Puola",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 146,
                            Abbreviation = "GQ",
                            Country = "Päiväntasaajan Guinea",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 147,
                            Abbreviation = "Q",
                            Country = "Qatar",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 148,
                            Abbreviation = "F",
                            Country = "Ranska",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 149,
                            Abbreviation = "RO",
                            Country = "Romania",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 150,
                            Abbreviation = "RWA",
                            Country = "Ruanda",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 151,
                            Abbreviation = "S",
                            Country = "Ruotsi",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 152,
                            Abbreviation = "SCN",
                            Country = "Saint Kitts ja Nevis",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 153,
                            Abbreviation = "WL",
                            Country = "Saint Lucia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 154,
                            Abbreviation = "WV",
                            Country = "Saint Vincent ja Grenadiinit",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 155,
                            Abbreviation = "D",
                            Country = "Saksa",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 156,
                            Abbreviation = "SOL",
                            Country = "Salomonsaaret",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 157,
                            Abbreviation = "Z",
                            Country = "Sambia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 158,
                            Abbreviation = "WS",
                            Country = "Samoa",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 159,
                            Abbreviation = "RSM",
                            Country = "San Marino",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 160,
                            Abbreviation = "STP",
                            Country = "São Tomé ja Príncipe",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 161,
                            Abbreviation = "SA",
                            Country = "Saudi-Arabia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 162,
                            Abbreviation = "SN",
                            Country = "Senegal",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 163,
                            Abbreviation = "SRB",
                            Country = "Serbia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 164,
                            Abbreviation = "SY",
                            Country = "Seychellit",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 165,
                            Abbreviation = "WAL",
                            Country = "Sierra Leone",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 166,
                            Abbreviation = "SGP",
                            Country = "Singapore",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 167,
                            Abbreviation = "SK",
                            Country = "Slovakia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 168,
                            Abbreviation = "SLO",
                            Country = "Slovenia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 169,
                            Abbreviation = "SO",
                            Country = "Somalia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 170,
                            Abbreviation = "CL",
                            Country = "Sri Lanka",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 171,
                            Abbreviation = "SUD",
                            Country = "Sudan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 172,
                            Abbreviation = "FIN",
                            Country = "Suomi",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 173,
                            Abbreviation = "SME",
                            Country = "Surinam",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 174,
                            Abbreviation = "SD",
                            Country = "Swazimaa",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 175,
                            Abbreviation = "CH",
                            Country = "Sveitsi",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 176,
                            Abbreviation = "SYR",
                            Country = "Syyria",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 177,
                            Abbreviation = "TJ",
                            Country = "Tadzikistan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 178,
                            Abbreviation = "RC",
                            Country = "Taiwan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 179,
                            Abbreviation = "EAT",
                            Country = "Tansania",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 180,
                            Abbreviation = "DK",
                            Country = "Tanska",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 181,
                            Abbreviation = "T",
                            Country = "Thaimaa",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 182,
                            Abbreviation = "TG",
                            Country = "Togo",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 183,
                            Abbreviation = "TO",
                            Country = "Tonga",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 184,
                            Abbreviation = "TT",
                            Country = "Trinidad ja Tobago",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 185,
                            Abbreviation = "TD",
                            Country = "Tšad;TCH",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 186,
                            Abbreviation = "CZ",
                            Country = "Tšekki",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 187,
                            Abbreviation = "TN",
                            Country = "Tunisia",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 188,
                            Abbreviation = "TR",
                            Country = "Turkki",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 189,
                            Abbreviation = "TM",
                            Country = "Turkmenistan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 190,
                            Abbreviation = "TUV",
                            Country = "Tuvalu",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 191,
                            Abbreviation = "EAU",
                            Country = "Uganda",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 192,
                            Abbreviation = "UA",
                            Country = "Ukraina",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 193,
                            Abbreviation = "H",
                            Country = "Unkari",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 194,
                            Abbreviation = "ROU",
                            Country = "Uruguay",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 195,
                            Abbreviation = "NZ",
                            Country = "Uusi-Seelanti",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 196,
                            Abbreviation = "UZ",
                            Country = "Uzbekistan",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 197,
                            Abbreviation = "BY",
                            Country = "Valko-Venäjä",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 198,
                            Abbreviation = "VU",
                            Country = "Vanuatu",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 199,
                            Abbreviation = "V",
                            Country = "Vatikaani",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 200,
                            Abbreviation = "YV",
                            Country = "Venezuela",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 201,
                            Abbreviation = "RUS",
                            Country = "Venäjä",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 202,
                            Abbreviation = "VN",
                            Country = "Vietnam",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 203,
                            Abbreviation = "EST",
                            Country = "Viro",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 204,
                            Abbreviation = "UAE",
                            Country = "Yhdistyneet Arabiemiirikunnat",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 205,
                            Abbreviation = "GB",
                            Country = "Yhdistynyt Kuningaskunta",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 206,
                            Abbreviation = "USA",
                            Country = "Yhdysvallat",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 207,
                            Abbreviation = "ZW",
                            Country = "Zimbabwe",
                            IsDiplomat = false
                        },
                        new
                        {
                            Id = 208,
                            Code = "10",
                            Country = "Saksa",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 209,
                            Code = "12",
                            Country = "Yhdysvallat",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 210,
                            Code = "14",
                            Country = "Argentiina",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 211,
                            Code = "15",
                            Country = "Itävalta",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 212,
                            Code = "16",
                            Country = "Belgia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 213,
                            Code = "17",
                            Country = "Brasilia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 214,
                            Code = "18",
                            Country = "Bulgaria",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 215,
                            Code = "19",
                            Country = "Kanada",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 216,
                            Code = "20",
                            Country = "Kiina",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 217,
                            Code = "21",
                            Country = "Etelä-Korea",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 218,
                            Code = "23",
                            Country = "Kuuba",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 219,
                            Code = "24",
                            Country = "Tanska",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 220,
                            Code = "25",
                            Country = "Egypti",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 221,
                            Code = "26",
                            Country = "Espanja",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 222,
                            Code = "27",
                            Country = "Ranska",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 223,
                            Code = "28",
                            Country = "Iso-Britannia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 224,
                            Code = "29",
                            Country = "Unkari",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 225,
                            Code = "30",
                            Country = "Intia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 226,
                            Code = "31",
                            Country = "Indonesia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 227,
                            Code = "32",
                            Country = "Irak",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 228,
                            Code = "33",
                            Country = "Israel",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 229,
                            Code = "34",
                            Country = "Italia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 230,
                            Code = "35",
                            Country = "Japani",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 231,
                            Code = "36",
                            Country = "Meksiko",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 232,
                            Code = "37",
                            Country = "Norja",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 233,
                            Code = "38",
                            Country = "Hollanti",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 234,
                            Code = "39",
                            Country = "Peru",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 235,
                            Code = "40",
                            Country = "Puola",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 236,
                            Code = "41",
                            Country = "Portugali",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 237,
                            Code = "42",
                            Country = "Romania",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 238,
                            Code = "43",
                            Country = "Ruotsi",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 239,
                            Code = "44",
                            Country = "Sveitsi",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 240,
                            Code = "46",
                            Country = "Turkki",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 241,
                            Code = "47",
                            Country = "Venäjä",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 242,
                            Code = "48",
                            Country = "Venezuela",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 243,
                            Code = "49",
                            Country = "Serbia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 244,
                            Code = "50",
                            Country = "Etelä-Afrikka",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 245,
                            Code = "51",
                            Country = "Kreikka",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 246,
                            Code = "55",
                            Country = "Itämeren suojelukomissio",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 247,
                            Code = "56",
                            Country = "Iran",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 248,
                            Code = "57",
                            Country = "UNU-WIDER",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 249,
                            Code = "58",
                            Country = "Chile",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 250,
                            Code = "59",
                            Country = "Viro",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 251,
                            Code = "60",
                            Country = "Latvia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 252,
                            Code = "61",
                            Country = "Irlanti",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 253,
                            Code = "62",
                            Country = "Ukraina",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 254,
                            Code = "63",
                            Country = "Slovakia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 255,
                            Code = "64",
                            Country = "Tšekki",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 256,
                            Code = "65",
                            Country = "Liettua",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 257,
                            Code = "66",
                            Country = "Kansainvälinen siirtolaisuusjärjestö",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 258,
                            Code = "67",
                            Country = "Marokko",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 259,
                            Code = "68",
                            Country = "Islanti",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 260,
                            Code = "69",
                            Country = "Kroatia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 261,
                            Code = "71",
                            Country = "Kypros",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 262,
                            Code = "74",
                            Country = "Tunisia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 263,
                            Code = "76",
                            Country = "Malesia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 264,
                            Code = "77",
                            Country = "Vietnam",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 265,
                            Code = "78",
                            Country = "Thaimaa",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 266,
                            Code = "79",
                            Country = "Euroopan kemikaalivirasto",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 267,
                            Code = "80",
                            Country = "Saudi-Arabia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 268,
                            Code = "82",
                            Country = "Georgia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 269,
                            Code = "83",
                            Country = "Pohjoismaiden investointipankki",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 270,
                            Code = "84",
                            Country = "Liberia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 271,
                            Code = "85",
                            Country = "Valko-Venäjä",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 272,
                            Code = "86",
                            Country = "Kazakstan",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 273,
                            Code = "87",
                            Country = "Kolumbia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 274,
                            Code = "88",
                            Country = "Uruguay",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 275,
                            Code = "89",
                            Country = "Palestiina",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 276,
                            Code = "90",
                            Country = "Namibia",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 277,
                            Code = "91",
                            Country = "Algeria",
                            IsDiplomat = true
                        },
                        new
                        {
                            Id = 278,
                            Code = "92",
                            Country = "Yhdistyneet arabiemiirikunnat",
                            IsDiplomat = true
                        });
                });

            modelBuilder.Entity("CarGame.Api.Entites.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DiplomatNumber")
                        .HasPrecision(2)
                        .HasColumnType("integer")
                        .HasColumnName("diplomat_number");

                    b.Property<bool>("IsDiplomat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_diplomat");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 3067)")
                        .HasColumnName("location");

                    b.Property<int>("PlateId")
                        .HasColumnType("integer")
                        .HasColumnName("plate_id");

                    b.HasKey("Id")
                        .HasName("pk_sightings");

                    b.HasIndex("PlateId")
                        .HasDatabaseName("ix_sightings_plate_id");

                    b.ToTable("sightings", null, t =>
                        {
                            t.HasCheckConstraint("CK_plate_id_diplomat_number", "is_diplomat = false OR (diplomat_number IS NOT NULL AND diplomat_number >= 1 AND diplomat_number <= 99)");
                        });
                });

            modelBuilder.Entity("CarGame.Api.Entites.Sighting", b =>
                {
                    b.HasOne("CarGame.Api.Entites.Plate", "Plate")
                        .WithMany()
                        .HasForeignKey("PlateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sightings_plates_plate_id");

                    b.Navigation("Plate");
                });
#pragma warning restore 612, 618
        }
    }
}
