INSERT INTO car_game.plates (country, country_abbreviation, diplomat_code, is_diplomat)
VALUES
    ('Afganistan', 'AFG', null, false),
    ('Alankomaat', 'NL', null, false),
    ('Alankomaiden Antillit', 'NA', null, false),
    ('Albania', 'AL', null, false),
    ('Alderney', 'GBA', null, false),
    ('Algeria', 'DZ', null, false),
    ('Andorra', 'AND', null, false),
    ('Angola', 'ANG', null, false),
    ('Antigua ja Barbuda', 'AG', null, false),
    ('Argentiina', 'RA', null, false),
    ('Armenia', 'AM', null, false),
    ('Australia', 'AUS', null, false),
    ('Azerbaidzhan', 'AZ', null, false),
    ('Bahamasaaret', 'BS', null, false),
    ('Bahrain', 'BRN', null, false),
    ('Bangladesh', 'BD', null, false),
    ('Barbados', 'BDS', null, false),
    ('Belgia', 'B', null, false),
    ('Belize', 'BH', null, false),
    ('Benin', 'DY', null, false),
    ('Bhutan', 'BHT', null, false),
    ('Bolivia', 'BOL', null, false),
    ('Bosnia-Hertsegovina', 'BIH', null, false),
    ('Botswana', 'BW', null, false),
    ('Brasilia', 'BR', null, false),
    ('Brittiläiset Neitsytsaaret', 'BVI', null, false),
    ('Brunei', 'BRU', null, false),
    ('Bulgaria', 'BG', null, false),
    ('Burkina Faso', 'BF', null, false),
    ('Burundi', 'RU', null, false),
    ('Chile', 'RCH', null, false),
    ('Costa Rica', 'CR', null, false),
    ('Dijibouti', 'DJI', null, false),
    ('Dominica', 'WD', null, false),
    ('Dominikaaninen tasavalta', 'DOM', null, false),
    ('Ecuador', 'EC', null, false),
    ('Egypti', 'ET', null, false),
    ('El Salvador', 'SV', null, false),
    ('Eritrea', 'ER', null, false),
    ('Espanja', 'E', null, false),
    ('Etelä-Afrikka', 'ZA', null, false),
    ('Etiopia', 'ETH', null, false),
    ('Fidzi', 'FJI', null, false),
    ('Filippiinit', 'RP', null, false),
    ('Färsaaret', 'FR', null, false),
    ('Gabon', 'G', null, false),
    ('Gambia', 'WAG', null, false),
    ('Georgia', 'GE', null, false),
    ('Ghana', 'GH', null, false),
    ('Gibraltar', 'GBZ', null, false),
    ('Grenada', 'WG', null, false),
    ('Grönlanti', 'KN', null, false),
    ('Guatemala', 'GCA', null, false),
    ('Guernsey', 'GBG', null, false),
    ('Guinea', 'RG', null, false),
    ('Guinea-Bissau', 'GNB', null, false),
    ('Guyana', 'GUY', null, false),
    ('Haiti', 'RH', null, false),
    ('Honduras', 'HN', null, false),
    ('Hong Kong', 'HK', null, false),
    ('Indonesia', 'RI', null, false),
    ('Intia', 'IND', null, false),
    ('Irak', 'IRQ', null, false),
    ('Iran', 'IR', null, false),
    ('Irlanti', 'IRL', null, false),
    ('Islanti', 'IS', null, false),
    ('Israel', 'IL', null, false),
    ('Italia', 'I', null, false),
    ('Itä-Timor', 'TL', null, false),
    ('Itävalta', 'A', null, false),
    ('Jamaika', 'JA', null, false),
    ('Japani', 'J', null, false),
    ('Jemen', 'YAR', null, false),
    ('Jersey', 'GBJ', null, false),
    ('Jordania', 'HKJ', null, false),
    ('Kambodzha', 'K', null, false),
    ('Kamerun', 'CAM', null, false),
    ('Kanada', 'CDN', null, false),
    ('Kap Verde', 'CV', null, false),
    ('Kazakstan', 'KZ', null, false),
    ('Kenia', 'EAK', null, false),
    ('Keski-Afrikan tasavalta', 'RCA', null, false),
    ('Kiinan kansantasavalta', 'PRC', null, false),
    ('Kirgisia', 'KS', null, false),
    ('Kiribati', 'KIR', null, false),
    ('Kolumbia', 'CO', null, false),
    ('Komorit', 'COM', null, false),
    ('Kongon demokraattinen tasavalta', 'ZRE', null, false),
    ('Kongon tasavalta', 'RCB', null, false),
    ('Korean demokraattinen kansantasavalta', 'DVRK', null, false),
    ('Korean tasavalta', 'ROK', null, false),
    ('Kosovo', 'RKS', null, false),
    ('Kreikka', 'GR', null, false),
    ('Kroatia', 'HR', null, false),
    ('Kuuba', 'CU', null, false),
    ('Kuwait', 'KWT', null, false),
    ('Kypros', 'CY', null, false),
    ('Laos', 'LAO', null, false),
    ('Latvia', 'LV', null, false),
    ('Lesotho', 'LS', null, false),
    ('Libanon', 'RL', null, false),
    ('Liberia', 'LB', null, false),
    ('Libya', 'LAR', null, false),
    ('Liechtenstein', 'FL', null, false),
    ('Liettua', 'LT', null, false),
    ('Luxemburg', 'L', null, false),
    ('Länsi-Sahara', 'DARS', null, false),
    ('Madagaskar', 'RM', null, false),
    ('Pohjois-Makedonia', 'NMK', null, false),
    ('Malawi', 'MW', null, false),
    ('Malediivit', 'MV', null, false),
    ('Malesia', 'MAL', null, false),
    ('Mali', 'RMM', null, false),
    ('Malta', 'M', null, false),
    ('Man-saari', 'GBM', null, false),
    ('Marokko', 'MA', null, false),
    ('Marshallinsaaret', 'MH', null, false),
    ('Mauritania', 'RIM', null, false),
    ('Mauritius', 'MS', null, false),
    ('Meksiko', 'MEX', null, false),
    ('Mikronesia', 'FSM', null, false),
    ('Moldova', 'MD', null, false),
    ('Monaco', 'MC', null, false),
    ('Mongolia', 'MGL', null, false),
    ('Montenegro', 'MNE', null, false),
    ('Mosambik', 'MOC', null, false),
    ('Myanmar', 'BUR', null, false),
    ('Namibia', 'NAM', null, false),
    ('Nauru', 'NAU', null, false),
    ('Nepal', 'NEP', null, false),
    ('Nicaragua', 'NIC', null, false),
    ('Niger', 'RN', null, false),
    ('Nigeria', 'WAN', null, false),
    ('Norja', 'N', null, false),
    ('Norsunluurannikko', 'CI', null, false),
    ('Oman', 'OM', null, false),
    ('Pakistan', 'PK', null, false),
    ('Palau', 'PAL', null, false),
    ('Palestiina', 'PS', null, false),
    ('Panama', 'PA', null, false),
    ('Papua-Uusi Guinea', 'PNG', null, false),
    ('Paraguay', 'PY', null, false),
    ('Peru', 'PE', null, false),
    ('Portugali', 'P', null, false),
    ('Puola', 'PL', null, false),
    ('Päiväntasaajan Guinea', 'GQ', null, false),
    ('Qatar', 'Q', null, false),
    ('Ranska', 'F', null, false),
    ('Romania', 'RO', null, false),
    ('Ruanda', 'RWA', null, false),
    ('Ruotsi', 'S', null, false),
    ('Saint Kitts ja Nevis', 'SCN', null, false),
    ('Saint Lucia', 'WL', null, false),
    ('Saint Vincent ja Grenadiinit', 'WV', null, false),
    ('Saksa', 'D', null, false),
    ('Salomonsaaret', 'SOL', null, false),
    ('Sambia', 'Z', null, false),
    ('Samoa', 'WS', null, false),
    ('San Marino', 'RSM', null, false),
    ('São Tomé ja Príncipe', 'STP', null, false),
    ('Saudi-Arabia', 'SA', null, false),
    ('Senegal', 'SN', null, false),
    ('Serbia', 'SRB', null, false),
    ('Seychellit', 'SY', null, false),
    ('Sierra Leone', 'WAL', null, false),
    ('Singapore', 'SGP', null, false),
    ('Slovakia', 'SK', null, false),
    ('Slovenia', 'SLO', null, false),
    ('Somalia', 'SO', null, false),
    ('Sri Lanka', 'CL', null, false),
    ('Sudan', 'SUD', null, false),
    ('Suomi', 'FIN', null, false),
    ('Surinam', 'SME', null, false),
    ('Swazimaa', 'SD', null, false),
    ('Sveitsi', 'CH', null, false),
    ('Syyria', 'SYR', null, false),
    ('Tadzikistan', 'TJ', null, false),
    ('Taiwan', 'RC', null, false),
    ('Tansania', 'EAT', null, false),
    ('Tanska', 'DK', null, false),
    ('Thaimaa', 'T', null, false),
    ('Togo', 'TG', null, false),
    ('Tonga', 'TO', null, false),
    ('Trinidad ja Tobago', 'TT', null, false),
    ('Tšad;TCH', 'TD', null, false),
    ('Tšekki', 'CZ', null, false),
    ('Tunisia', 'TN', null, false),
    ('Turkki', 'TR', null, false),
    ('Turkmenistan', 'TM', null, false),
    ('Tuvalu', 'TUV', null, false),
    ('Uganda', 'EAU', null, false),
    ('Ukraina', 'UA', null, false),
    ('Unkari', 'H', null, false),
    ('Uruguay', 'ROU', null, false),
    ('Uusi-Seelanti', 'NZ', null, false),
    ('Uzbekistan', 'UZ', null, false),
    ('Valko-Venäjä', 'BY', null, false),
    ('Vanuatu', 'VU', null, false),
    ('Vatikaani', 'V', null, false),
    ('Venezuela', 'YV', null, false),
    ('Venäjä', 'RUS', null, false),
    ('Vietnam', 'VN', null, false),
    ('Viro', 'EST', null, false),
    ('Yhdistyneet Arabiemiirikunnat', 'UAE', null, false),
    ('Yhdistynyt Kuningaskunta', 'GB', null, false),
    ('Yhdysvallat', 'USA', null, false),
    ('Zimbabwe', 'ZW', null, false),
    ('Saksa', null, '10', true),
    ('Yhdysvallat', null, '12', true),
    ('Argentiina', null, '14', true),
    ('Itävalta', null, '15', true),
    ('Belgia', null, '16', true),
    ('Brasilia', null, '17', true),
    ('Bulgaria', null, '18', true),
    ('Kanada', null, '19', true),
    ('Kiina', null, '20', true),
    ('Etelä-Korea', null, '21', true),
    ('Kuuba', null, '23', true),
    ('Tanska', null, '24', true),
    ('Egypti', null, '25', true),
    ('Espanja', null, '26', true),
    ('Ranska', null, '27', true),
    ('Iso-Britannia', null, '28', true),
    ('Unkari', null, '29', true),
    ('Intia', null, '30', true),
    ('Indonesia', null, '31', true),
    ('Irak', null, '32', true),
    ('Israel', null, '33', true),
    ('Italia', null, '34', true),
    ('Japani', null, '35', true),
    ('Meksiko', null, '36', true),
    ('Norja', null, '37', true),
    ('Hollanti', null, '38', true),
    ('Peru', null, '39', true),
    ('Puola', null, '40', true),
    ('Portugali', null, '41', true),
    ('Romania', null, '42', true),
    ('Ruotsi', null, '43', true),
    ('Sveitsi', null, '44', true),
    ('Turkki', null, '46', true),
    ('Venäjä', null, '47', true),
    ('Venezuela', null, '48', true),
    ('Serbia', null, '49', true),
    ('Etelä-Afrikka', null, '50', true),
    ('Kreikka', null, '51', true),
    ('Itämeren suojelukomissio', null, '55', true),
    ('Iran', null, '56', true),
    ('UNU-WIDER', null, '57', true),
    ('Chile', null, '58', true),
    ('Viro', null, '59', true),
    ('Latvia', null, '60', true),
    ('Irlanti', null, '61', true),
    ('Ukraina', null, '62', true),
    ('Slovakia', null, '63', true),
    ('Tšekki', null, '64', true),
    ('Liettua', null, '65', true),
    ('Kansainvälinen siirtolaisuusjärjestö', null, '66', true),
    ('Marokko', null, '67', true),
    ('Islanti', null, '68', true),
    ('Kroatia', null, '69', true),
    ('Kypros', null, '71', true),
    ('Tunisia', null, '74', true),
    ('Malesia', null, '76', true),
    ('Vietnam', null, '77', true),
    ('Thaimaa', null, '78', true),
    ('Euroopan kemikaalivirasto', null, '79', true),
    ('Saudi-Arabia', null, '80', true),
    ('Georgia', null, '82', true),
    ('Pohjoismaiden investointipankki', null, '83', true),
    ('Liberia', null, '84', true),
    ('Valko-Venäjä', null, '85', true),
    ('Kazakstan', null, '86', true),
    ('Kolumbia', null, '87', true),
    ('Uruguay', null, '88', true),
    ('Palestiina', null, '89', true),
    ('Namibia', null, '90', true),
    ('Algeria', null, '91', true),
    ('Yhdistyneet arabiemiirikunnat', null, '92', true);
